Merge

diff --git a/.cloudbees/scanners/binary_scan.yaml b/.cloudbees/scanners/binary_scan.yaml
--- a/.cloudbees/scanners/binary_scan.yaml
+++ b/.cloudbees/scanners/binary_scan.yaml
@@ -8,6 +8,61 @@ jobs:
       - name: Initiate execution plan
         uses: cloudbees-io/asset-chain-utils-preprod/start-chain@v1
         id: plan
+
+      - name: Setup git credentials
+        continue-on-error: true
+        uses: cloudbees-io/configure-git-global-credentials@v1
+
+      - name: Login to AWS
+        uses: cloudbees-io/configure-aws-credentials@v1
+        id: aws-login
+        continue-on-error: true
+        with:
+          aws-region: us-east-1
+          role-to-assume: ${{ vars.oidc_staging_iam_role }}
+          role-duration-seconds: "3600"
+
+      - name: Configure container registry for Staging ECR
+        continue-on-error: true
+        uses: cloudbees-io/configure-ecr-credentials@v1
+
+      - id: cranepull
+        continue-on-error: true
+        name: crane pull
+        uses: docker://gcr.io/go-containerregistry/crane:debug
+        run: |
+          set -uo pipefail
+          
+          if [ ! -e resolved-image.file ]; then
+            echo '020229604682.dkr.ecr.us-east-1.amazonaws.com/services/asset-service:0.0.6170' > resolved-image.file
+          fi
+
+          set +e
+          
+          image_with_digest=
+          while IFS= read -r line; do
+            echo "Getting image digest of source image ${line}"
+            image_with_digest=$(crane digest ${line} --full-ref --platform all)
+          
+            if [ $? -ne 0 ]; then
+              echo "Failed get image digest: $line"
+              image_with_digest=
+              continue
+            fi
+          
+            echo "Found source image to pull: ${image_with_digest}"
+            crane pull ${image_with_digest} image.tar.gz
+            ls -alt
+          
+            if [ $? -ne 0 ]; then
+              echo "Failed to pull image: $line"
+              image_with_digest=
+              continue
+            fi
+            break
+          done < "resolved-image.file"
+          
+          set -e        
         
       - name: Workflow Artifact Inventory
         if: ${{ steps.plan.outputs.wfartifact-inventory == 'true' }}
